site_name: "PVGIS API Reference"
site_author: Nikos Alexandris
# site_url: {{site_url: null}: null}

nav:
  - Introduction: index.md
  - Overview: overview.md
  - Summary: SUMMARY.md
  - Code Reference: reference/  
  # rest of the navigation...
  # - Basic Usage: basic_usage.md
  # - Configuration: configuration.md
  # - Update: update.md
  # - Advanced Usage:
      # - Projects: projects.md
      # - Tags: tags.md

theme:
  name: material
  custom_dir: overrides
  logo: images/pvgis_image_squared.png
  palette:
    # - primary: yellow
    # primary: blue grey
    # accent: light blue
    - media: "(prefers-color-scheme: light)"
      scheme: yellow
      toggle:
        icon: material/brightness-6
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-3
        name: Switch to light mode
  features:
    - announce.dismiss
    - header.autohide
    - navigation.top

extra_css:
  - stylesheets/extra.css
  - stylesheets/links.css

plugins:
  - search
  - autolinks
  - autorefs
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true
  - gen-files:
      scripts:
        - scripts/generate_reference_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          import:
            - url: https://docs.python-requests.org/en/master/objects.inv
              domains: [std, py]
          paths: [.]


markdown_extensions:
  - admonition
  - meta
  - toc:
      permalink: true
      baselevel: 2
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  # - pymdownx.emoji:
  #     emoji_generator: !%21python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

repo_name: pvis-be-prototype
repo_url: https://gitlab.jrc.ec.europa.eu/jrc-projects/pvgis/pvis-be-prototype.git
