site_name: PVGIS
site_description: Photovoltaic Geographical Information System
site_author: Nikos Alexandris and the PVGIS team
site_url: http://pvgis-reference.jrc.it

repo_name: pvis-be-prototype
repo_url: https://gitlab.jrc.ec.europa.eu/jrc-projects/pvgis/pvis-be-prototype.git
edit_uri: edit/mkdocs/docs/
# Keep this in sync with pyproject.toml and index.md
copyright: Copyright &copy; 2023 European Commission. Licensed under the EUPL-1.2 or later

watch:
  - docs/includes

nav:
  - Overview:
    - Overview: index.md
    - Site tree: site_tree.md
    - License: license.md
    - Credits: credits.md
  - Installation:
    - install/index.md
    # - install/install.md
  - Tutorials:
    - tutorials/index.md
    - tutorials/introduction.md
    - Solar Position:
      - tutorials/solar_position.md
      - 󰆊 Comparing Algorithms: notebooks/solar_position_pvgis_noaa_vs_other_models.ipynb
    - Surface Position Optimization: notebooks/surface_position_optimization_examples.ipynb 
    - tutorials/solar_irradiance.md
    - tutorials/photovoltaic_performance.md
  - CLI:
    - cli/index.md
    - cli/features.md
    - cli/basics.md
    - cli/verbosity.md
    - cli/symbols.md
    - cli/timestamps.md
    - cli/precision.md
    - cli/plots.md
    - cli/fingerprint.md
    - cli/qrcode.md
    - cli/metadata.md
    - cli/numpy.md
    - cli/logging.md
    - Power:
      - Introduction: cli/power/introduction.md
      - Tools: cli/power/tools.md
      - Broadband: cli/power/broadband.md
      - Spectrally Resolved: cli/power/spectral.md
      - Spectral Effect: cli/power/spectral_effect.md
    - Irradiance:
      - Introduction: cli/irradiance/introduction.md
      - Tools: cli/irradiance/tools.md
      - Global: cli/irradiance/global.md
      - Direct: cli/irradiance/direct.md
      - Diffuse: cli/irradiance/diffuse.md
      - Reflected: cli/irradiance/reflected.md
    - Position:
      - Introduction: cli/position/introduction.md
      - Tools: cli/position/tools.md
      - Overview: cli/position/overview.md
      - Solar Time: cli/position/time.md
      - Incidence: cli/position/incidence.md
  - Web API:
    - web_api/index.md
    - web_api/install.md
    - web_api/run.md
    - web_api/examples.md
  - API:
    - api/index.md
    - api/position.md
    - api/power.md
  - Reference:
    - reference/index.md
    - Photovoltaic Production:
      - Solar Position: reference/solar_position.md
      - Solar Irradiance: reference/solar_irradiance.md
      - Photovoltaic Performance: reference/photovoltaic_performance.md
    - Time Series Data: reference/time_series_data.md
    - reference/comparison_pvgis_v6_vs_pvgis52.md
    # - reference/pvgis52.md
    # - reference/pvgis52_rsun_standalone_opt.md
    - reference/web_traffic.md
    - reference/external_tools.md
    - reference/external_resources.md
  - Source Code:
    - source_code/index.md
    - Architecture: source_code/architecture.md
    - Dependencies: source_code/dependencies.md
    - Custom Data Classes: source_code/custom_data_classes.md
    - Duck Arrays: source_code/duck_arrays.md
    - Algorithms: source_code/algorithms.md
    - API: source_code/api.md
    - CLI: source_code/cli.md
    - Web API: source_code/web_api.md
    - Logger: source_code/logger.md
  - Development:
    - development/index.md
    - development/gantt.md
    - Roadmap:
      - development/roadmap_and_progress.md
      - Components:
        - development/solar_position.md
        - development/solar_irradiance.md
        - development/photovoltaic_performance.md
        - development/topography.md
    - development/conventions.md
    - development/optimisation.md
    - development/profiling.md
    - development/contribution_guidelines.md
    - development/adding_new_features.md
    - development/pytest.md
    # - development/state_and_future_of_pvgis.md
    # - 󰦕 Test Coverage: coverage.md
    # - Test Coverage: development/coverage_html/index.html
  - Tags: includes/tags.md

extra:
  tags:
    Concepts: concepts
    Chunking: chunking
    CLI: cli
    How-To: howto
    To Do: todo
    See-Also: seealso

theme:
  font: false
  logo: images/pvgis_image_squared.png
  icon:
    tag:
      concepts: simple/blueprint
      chunking: fontawesome/solid/cubes-stacked
      cli: octicons/terminal-16
      howto: material/tools
      todo: octicons/tasklist-16
      seealso: material/eye
  name: material
  custom_dir: docs/overrides
  palette:
    # - primary: yellow
    # primary: blue grey
    # accent: light blue
    - media: "(prefers-color-scheme: light)"
      scheme: yellow
      toggle:
        icon: material/brightness-6
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: blue
      toggle:
        icon: material/brightness-3
        name: Switch to light mode
  features:
    - announce.dismiss
    - header.autohide
    - search.highlight
    - search.share
    - content.tooltips
    - content.code.copy
    - content.action.view
    - content.action.edit
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    # - navigation.prune 
    - navigation.expand
    - navigation.path
    - navigation.indexes 
    - toc.follow
    - toc.integrate 
    - navigation.footer

extra_css:
  - stylesheets/extra.css
  - stylesheets/links.css
  - stylesheets/code_select.css
  - stylesheets/mermaid.css
  # - stylesheets/tufte-sidebars.css
  - css/termynal.css
  - css/custom.css
  - css/mkdocstrings.css
# - css/style.css
# - css/material.css

markdown_extensions:
  - extra
  # - mdx_include:
  #     base_path: docs
  - meta
  - toc:
      permalink: true # Paragraph symbol linking to current headline
      baselevel: 2
  - footnotes
  - def_list
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.magiclink
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.critic:
      mode: view
  - pymdownx.details
  # - markdown.extensions.codehilite:
  #     guess_lang: false
  - codehilite
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      pygments_lang_class: true
      # linenums: true
      line_spans: __span
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - abbr
  - pymdownx.snippets:
      auto_append:
        - docs/includes/abbreviations.md
      # check_paths: True
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
          # format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - js/termynal.js
  - js/custom.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - js/tablesort.js
  - js/mermaid_config.js
  - js/extra-loader.js

plugins:
  - search
  - badges
  - pagetree
  - section-index
  - mermaid2
  - bibtex:
      bib_file: "references.bib"
  - tags:
      tags_file: includes/tags.md
  - table-reader
  - exclude:
      glob:
        - "*.py"  # Python scripts
        - "*.inc"  # includes
  # - coverage:
      # html_report_dir: docs/development/coverage_html
      # page_name: coverage  # default
  - markdown-exec:
      ansi: required
  - autorefs
  - git-revision-date-localized:
      type: timeago
      fallback_to_build_date: false
      enable_creation_date: true
      # exclude:
          # - coverage.md
      # enabled: true
      # strict: true
  # - git-committers:
  #     gitlab_repository: 12345678
  #     token: !ENV ["GH_TOKEN"]
  - minify:
      minify_html: true
  - mkdocstrings:
      handlers:
        python:
          import:
          # - url: https://docs.python-requests.org/en/master/objects.inv
          #   domains: [std, py]
          - https://docs.python.org/3/objects.inv
          # - https://installer.readthedocs.io/en/stable/objects.inv  # demonstration purpose in the docs
          - https://mkdocstrings.github.io/autorefs/objects.inv
          paths: [.]
          options:
            # docstring_options:
            #   ignore_init_summary: true
            docstring_style: numpy
            docstring_section_style: table
            filters: ["!^_"]
            heading_level: 1
            inherited_members: true
            merge_init_into_class: true
            separate_signature: true
            line_length: 60
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true
            show_bases: true
  - mkdocs-jupyter:
          execute: true
          include_source: True
          # ignore: ["coverage.md"]

# extra:
#   social:
    # - icon: fontawesome/brands/gitlab-alt
    #   link: https://gitlab.jrc.ec.europa.eu/jrc-projects/pvgis/pvis-be-prototype
    # - icon: fontawesome/brands/twitter
    #   link: 
    # - icon: fontawesome/brands/linkedin
    #   link:
    # - icon: fontawesome/brands/dev
    #   link: https://dev.to/nikosalexandris
    # - icon: fontawesome/brands/medium
    #   link:
    # - icon: fontawesome/solid/globe
    #   link: https://joint-research-centre.ec.europa.eu/photovoltaic-geographical-information-system-pvgis_en
