site_name: PVGIS
site_description: Photovoltaic Geographical Information System
site_author: Nikos Alexandris and the PVGIS team
site_url: http://pvgis-reference.jrc.it

repo_name: pvis-be-prototype
repo_url: https://gitlab.jrc.ec.europa.eu/jrc-projects/pvgis/pvis-be-prototype.git
edit_uri: edit/main/docs/
# Keep this in sync with pyproject.toml and index.md
copyright: Copyright &copy; 2023 European Commission. Licensed under the EUPL-1.2 or later

watch:
  - docs/includes

nav:
  - Overview:
    - '': index.md
  - Installation: install/install.md
  - Tutorials:
    - tutorials/index.md
  - How To:
    - how_to/index.md
    - how_to/help.md
    - Power: how_to/power.md
  - Reference:
    - reference/index.md
  - Code Reference:
    - code_reference/index.md
    - Algorithms: code_reference/algorithms.md
    - CLI: code_reference/cli_reference.md
    - API: code_reference/api_reference.md
    - Web API: code_reference/web_api_reference.md
  - Tags: includes/tags.md

extra:
  tags:
    Concepts: concepts
    Chunking: chunking
    CLI: cli
    How-To: howto
    To Do: todo
    See-Also: seealso

theme:
  logo: images/pvgis_image_squared.png
  font:
    code: Source Code Pro
  icon:
    tag:
      concepts: simple/blueprint
      chunking: fontawesome/solid/cubes-stacked
      cli: octicons/terminal-16
      howto: material/tools
      todo: octicons/tasklist-16
      seealso: material/eye
  name: material
  custom_dir: docs/overrides
  palette:
    # - primary: yellow
    # primary: blue grey
    # accent: light blue
    - media: "(prefers-color-scheme: light)"
      scheme: yellow
      toggle:
        icon: material/brightness-6
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-3
        name: Switch to light mode
  features:
    - announce.dismiss
    - header.autohide
    - search.highlight
    - search.share
    - content.tooltips
    - content.action.edit
    - content.action.view
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    # - navigation.expand
    - navigation.path
    - navigation.indexes 
    - toc.follow
    - navigation.top
    - navigation.footer

extra_css:
  - stylesheets/extra.css
  - stylesheets/links.css
  - stylesheets/code_select.css
  - css/termynal.css
  - css/custom.css
  - css/mkdocstrings.css
# - css/style.css
# - css/material.css

markdown_extensions:
  - extra
  - mdx_include:
      base_path: docs
  - meta
  - toc:
      permalink: true # Paragraph symbol linking to current headline
      baselevel: 2
  - footnotes
  - def_list
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.magiclink
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic
  - pymdownx.critic:
      mode: view
  - pymdownx.details
  # - markdown.extensions.codehilite:
  #     guess_lang: false
  - codehilite
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      pygments_lang_class: true
      # linenums: true
      line_spans: __span
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - abbr
  - pymdownx.snippets:
      auto_append:
        - docs/includes/abbreviations.md
      # check_paths: True
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ''
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  # - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid@8.4.6/dist/mermaid.min.js
  - js/termynal.js
  - js/custom.js

plugins:
  - search
  - bibtex:
      bib_file: "references.bib"
  - tags:
      tags_file: includes/tags.md
  - table-reader
  - exclude:
      glob:
        - "*.py"  # Python scripts
        - "*.inc"  # includes
  - markdown-exec
  - autolinks
  - autorefs
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true
  # - gen-files:
  #     scripts:
  #       - scripts/generate_reference_pages.py
  # - literate-nav:
  #     nav_file: SUMMARY.md
  # - section-index
  # - include-markdown
  - mkdocstrings:
      handlers:
        python:
          import:
          # - url: https://docs.python-requests.org/en/master/objects.inv
          #   domains: [std, py]
          - https://docs.python.org/3/objects.inv
          # - https://installer.readthedocs.io/en/stable/objects.inv  # demonstration purpose in the docs
          - https://mkdocstrings.github.io/autorefs/objects.inv
          paths: [.]
          options:
            # docstring_options:
            #   ignore_init_summary: true
            docstring_style: numpy
            docstring_section_style: table
            filters: ["!^_"]
            heading_level: 1
            inherited_members: true
            merge_init_into_class: true
            separate_signature: true
            line_length: 60
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true

# extra:
#   social:
    # - icon: fontawesome/brands/gitlab-alt
    #   link: https://gitlab.jrc.ec.europa.eu/jrc-projects/pvgis/pvis-be-prototype
    # - icon: fontawesome/brands/twitter
    #   link: 
    # - icon: fontawesome/brands/linkedin
    #   link:
    # - icon: fontawesome/brands/dev
    #   link: https://dev.to/nikosalexandris
    # - icon: fontawesome/brands/medium
    #   link:
    # - icon: fontawesome/solid/globe
    #   link: https://joint-research-centre.ec.europa.eu/photovoltaic-geographical-information-system-pvgis_en
