site_name: PVGIS Reference
site_author: Nikos Alexandris and the PVGIS team
site_url: http://pvgis-reference.jrc.it

repo_name: pvis-be-prototype
repo_url: https://gitlab.jrc.ec.europa.eu/jrc-projects/pvgis/pvis-be-prototype.git
copyright: Copyright &copy; 2023 European Commission

nav:
  - Introduction: index.md
  - Overview: overview.md
  - Summary: SUMMARY.md
  - Code Reference: reference/  
  # rest of the navigation...
  # - Basic Usage: basic_usage.md
  # - Configuration: configuration.md
  # - Update: update.md
  # - Advanced Usage:
      # - Projects: projects.md
      # - Tags: tags.md

theme:
  name: material
  custom_dir: docs/overrides
  logo: images/pvgis_image_squared.png
  palette:
    # - primary: yellow
    # primary: blue grey
    # accent: light blue
    - media: "(prefers-color-scheme: light)"
      scheme: yellow
      toggle:
        icon: material/brightness-6
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-3
        name: Switch to light mode
  features:
    - announce.dismiss
    - header.autohide
    - navigation.top

extra_css:
  - stylesheets/extra.css
  - stylesheets/links.css
  - stylesheets/code_select.css
  - css/termynal.css
  - css/custom.css

extra_javascript:
  - https://unpkg.com/mermaid@8.4.6/dist/mermaid.min.js
  - js/termynal.js
  - js/custom.js

plugins:
  - search
  - autolinks
  - autorefs
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true
  - gen-files:
      scripts:
        - scripts/generate_reference_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      handlers:
        python:
          import:
            - url: https://docs.python-requests.org/en/master/objects.inv
              domains: [std, py]
          paths: [.]


markdown_extensions:
  - admonition
  - meta
  - toc:
      permalink: true
      baselevel: 2
  - markdown.extensions.codehilite:
      guess_lang: false
  - codehilite
  - extra
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ''
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
  - mdx_include:
      base_path: docs
  # Enable while writing docs to simplify highlighting
  # - pymdownx.highlight:
  #     linenums: true

# extra:
#   social:
    # - icon: fontawesome/brands/gitlab-alt
    #   link: https://gitlab.jrc.ec.europa.eu/jrc-projects/pvgis/pvis-be-prototype
    # - icon: fontawesome/brands/twitter
    #   link: 
    # - icon: fontawesome/brands/linkedin
    #   link:
    # - icon: fontawesome/brands/dev
    #   link: https://dev.to/nikosalexandris
    # - icon: fontawesome/brands/medium
    #   link:
    # - icon: fontawesome/solid/globe
    #   link: https://joint-research-centre.ec.europa.eu/photovoltaic-geographical-information-system-pvgis_en
