name: ValuesOutOfRange
description:

fields:

  out_of_range:
    type: ndarray
    title: Outbound ⊖
    description: Out of range values in the NumPy array 'value'
    symbol: ⊖
    initial: null
  
  out_of_range_index:
    type: ndarray
    title: Outbound ⊖ i
    description: Index of out-of-range values in the NumPy array 'value'
    symbol: ⊖ i
    initial: null
